CREATE TABLE board (
    num INT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(20) NOT NULL,
    name VARCHAR(50) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    regist_day DATETIME NOT NULL,
    hit INT DEFAULT 0,
    file_name VARCHAR(255) DEFAULT NULL,
    file_type VARCHAR(255) DEFAULT NULL,
    file_copied VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;